### ISSUE TITLE
[提議]: 增加DM指令

### ISSUE THREAD

**Issue by Skiawm91** [Youzi9601/YZBot#23]
### 你希望有什麽功能？

使用/dm
功能 /dm 給誰: 訊息:
fun按鈕
使用 /fun-button contents: 圖片link:
按下後跳出的圖片(以只有使用者才能看到的形式)

(contents)
神秘按鈕

大概這樣

**Comment by Youzi9601** [comment]
這功能將會在14天內用好，我不小心將djs13 升級到djs14 www

**Comment by Youzi9601** [comment]
目前 v14 的各功能正在重新添加回去，基本內容大致還是一樣，但是`按下後跳出的圖片(以只有使用者才能看到的形式)`這東西我將會用其他形式來表現uwub

**Comment by Youzi9601** [comment]
新版本將會定案於 /bot dm
