### ISSUE TITLE
[錯誤]: 分片

### ISSUE THREAD

**Issue by Swarmed2674** [Youzi9601/YZBot#25]
### 這是否存在於現有問題？

- [X] 我已經搜索了現有的問題

### 描述問題

分片部份似乎出了問題
提供代碼來解決問題 (i don't work)

	<client>.on("ready", async () => {
  		console.log("Online!")

### 發生當下

1.輸入命令 2.錯誤

### 版本

```Markdown
- Node:16
- npm:9
- YZB:最新版
```

### 相關日誌輸出

```Shell
No...
```

### 行為守則

- [X] 我同意遵守該項目的行為準則與確認問題無誤！

**Comment by Youzi9601** [comment]
近期將會開始將部分命令全部升級為v14，目前版本的事都沒問題的。
