### ISSUE TITLE
[提議]: 代幣與商店系統

### ISSUE THREAD

**Issue by Skiawm91** [Youzi9601/YZBot#48]
### 你希望有什麽功能？

用戶用 /money-set 註冊代幣包包
然後 /work 工作 可用 /money-admin setworkmoney: 設定最低與最高
使用 /play money: 玩遊戲 (輸[填的money]) 贏翻倍
然後config.json裡的擁有者可以使用/money-admin
 跟上面一樣 coin-add，增加錢 coin-remove 相反
/store 模式: [瀏覽/編輯(擁有者)]
只能在config.json裡的主要伺服器使用

### 功能的詳細描述？

真的看起來很難，所以其實不用做也沒關係

**Comment by Youzi9601** [comment]
這功能早已有想法，將會排在等級系統後面，將會定案為
/economy 系列命令
因為我儲存系統已經部分完善，應該是不太會有其他問題的。
